### ISSUE TITLE
Audit Menu missing

### ISSUE THREAD

**Issue by ChristopheMediane** [sybrew/The-SEO-Framework-Extension-Manager#49] opened 2021-12-02 10:54 UTC
Hi. I just installed the extension manager, I enabled it, but nothing happens. 
I don't have any Audit Menu on the SEO capabilities. 
Did I miss something ? 
Thanks for your help !
Christophe
![Capture d’écran 2021-12-02 à 11 52 40](https://user-images.githubusercontent.com/61502309/144408770-ca8b36ef-c870-464c-aab8-53c371c99317.png
![Capture d’écran 2021-12-02 à 11 54 24](https://user-images.githubusercontent.com/61502309/144408878-14026d41-fac6-45f2-bc6b-c1074edfb2ee.png)
)

**Comment by sybrew** [comment] 2021-12-06 21:00
Duplicate of #50, continuing there.

**Closed by sybrew** 2021-12-06 21:00 UTC
