### ISSUE TITLE
Dynamically generated titles and meta descriptions.

### ISSUE THREAD

**Issue by SarahHaruel** [sybrew/The-SEO-Framework-Extension-Manager#10] opened 2019-01-23 04:46 UTC
Hi Sybrew,

just  quick question.

I am currently using the Yoast SEO plugin and used the SEO migrator tool to bring my data per to your SEO framework plugin.

Whislt it brought pretty much everything over, i was a little surprised that it did not bring over my dynamically crafted titles and meta descriptions for my pages, categories, tags and posts.
 
Is this available in the plugin as I had to uninstall the plugin as it would have created massive problems for our website which has 1000's of pages, tags and posts.

Have I overlooked a setting to get this enabled ?

![dynamic_titles_descriptions](https://user-images.githubusercontent.com/37814137/51583455-8e3a7900-1ec8-11e9-8fc0-e4f98c7f15e9.jpg)

**Comment by sybrew** [comment] 2019-01-23 18:32
Unfortunately, this feature isn't implemented; I wanted to keep things simple and straightforward. Most users are unaware that such settings impose unwanted side-effects when misused. What's provided in The SEO Framework generally helps copywriters do the right thing while giving them the freedom to adjust whenever required.

Alas, this means that migrating with highly customized settings (as you have) won't always be feasible. I am afraid this is the situation you're in deep.

This isn't to say it'll never be possible. It's already under consideration, and I'm closing this issue as a duplicate of https://github.com/sybrew/the-seo-framework/issues/140

Please follow up there, definitely so when you have any special wishes 👍

**Closed by sybrew** 2019-01-23 18:32 UTC
